### ISSUE TITLE
Claims a plane is not a plane, with 100% certainty that it is a plane.

### ISSUE THREAD

**Issue by Blitheness** [what-plane/what-plane-frontend#21]
![image](https://user-images.githubusercontent.com/19779808/107127526-90ed4880-68ae-11eb-8bb7-a508446c4d3c.png)

**Comment by Will282** [comment]
Solution: Change text when ImageNet prediction is returned

"Hey, it looks like you've uploaded a picture that doesn't have a plane in it!"
Change the word "plane"
